### ISSUE TITLE
Code highlight issue in Server project

### ISSUE THREAD

**Issue by cotyar** [fable-compiler/fable-suave-scaffold#98] opened 2017-04-13 14:45 UTC
Hi guys! And thanks for an absolutely fantastic project!

Having an annoying issue when running it in Visual Studio Code.
Only applies to the Server project.
It all builds and runs fine but the editor itself doesn't recognise (highlights opens with red) namespaces imported with paket in Server.fs and Program.fs but doesn't complain and works well in Shared/Domain.fs.
No issues with Client project either.

Is it something wrong with my setup or a common issue?

Tried on both Mac and Win.

Many thanks 
Yuriy
![image](https://cloud.githubusercontent.com/assets/4975981/25009945/5710fb1a-2060-11e7-955e-c251089313e0.png)

**Comment by alfonsogarciacaro** [comment] 2017-04-13 15:00
Hi @cotyar, thanks for reporting! This is a known issue and will be fixed soon, you can follow the progress here: https://github.com/fsharp/FsAutoComplete/pull/158

**Comment by cotyar** [comment] 2017-04-13 15:04
Thank you Alfonso!
I thought I spoiled something ;-))
Have a great Easter!

**Comment by cotyar** [comment] 2017-04-20 10:22
Hi @alfonsogarciacaro 
The FsAC issue looks fixed and merged by Enrico on the 13th and Ionide was also updated to 2.25.9 same day.
Unfortunately the code highlight is still broken in my environment. 
Is it an issue with my env or the FsAC fix isn't finished yet please?

**Comment by alfonsogarciacaro** [comment] 2017-04-20 11:07
@cotyar For some reason it seems sometimes the intellisense takes a long time before activating (we need to check that), like a couple of minutes. Could you please try opening the project, leave it some minutes for reflection and check if the intellisense is activated?

**Comment by Krzysztof-Cieslak** [comment] 2017-04-20 11:10
Uhh... what?

**Comment by alfonsogarciacaro** [comment] 2017-04-20 11:29
@Krzysztof-Cieslak Yes, it happens to me sometimes with the new project format after last FSAC update (at least for Fable projects). It think at least @Zaid-Ajaj had a similar situation. I haven't checked the exact conditions to reproduce it yet. I commented it with @enricosada but at the moment we thought it was because I was using a Debug build of FSAC.

@cotyar Please also make sure you have installed the dependencies: `npm install; dotnet restore` and try reloading the window if necessary.

**Comment by enricosada** [comment] 2017-04-20 11:57
@alfonsogarciacaro afaik is correct and new ionide works, but i really tried with elmish and others.
I'll check `Server` asap. An ionide log may help.

About performance for parsing, i added https://github.com/fsharp/FsAutoComplete/issues/161 and i discussed with @efvincent who was trying to improve perf based on that for his scenario (lots of small projects with deep projectrefs)

https://fsharp.slack.com/archives/C1KANN0BV/p1492580157402324
>  I was able to make good progress with FSAC in addressing the specific problem I was seeing. I have more work to do but it seems in fairly easy reach to be able to deal with large sets of projects.
In my local build with 35 or so projects I'm able to get autocomplete and tooltips with a lag of < 120 seconds from the initial compile for the top level (deepest in the dep tree). Less for less dependent projects, down to < 20 seconds for the project with no dependencies.

**Comment by cotyar** [comment] 2017-04-20 12:22
@alfonsogarciacaro @enricosada - I've taken the latest zip from this repo, ran "npm install" and "./build.sh run" on it, opened in VSCode and it still has the same issue (please see attached).
Happy to provide ionide log but not sure where to get it from please *-(
Don't see them in "~/.vscode/extensions/Ionide.ionide-fsharp-2.25.9/".
<img width="1315" alt="screen shot 2017-04-20 at 13 12 03" src="https://cloud.githubusercontent.com/assets/4975981/25230585/62f0d48e-25cc-11e7-9142-1dde1e26acc7.png">

**Comment by alfonsogarciacaro** [comment] 2017-04-20 12:56
@cotyar Sorry, seems the problem comes from a change I did to the `Run` build target. I'll fix it. For now, you can just solve the problem by running `dotnet restore` in the `src/Server` directory.

**Comment by enricosada** [comment] 2017-04-20 12:57
i can repro.
seem no `obj` dir is created by restore, i'll check

**Comment by enricosada** [comment] 2017-04-20 13:00
yes, with `dotnet restore` works. good 😄

**Comment by enricosada** [comment] 2017-04-20 13:07
added https://github.com/enricosada/dotnet-proj-info/issues/3 to improve the error message (the same seen in ionide log btw) if project is not restored

**Comment by cotyar** [comment] 2017-04-20 13:48
@enricosada @alfonsogarciacaro thanks guys a lot! 
dotnet restore worked on the newly unzipped version but not on the old one (taken a month or so back and recently sync-ed with the latest). Which is a bit weird but hopefully will be solvable by comparing the proj and build files (will update you with the result).
Where can I find the ionide logs please? (Mac)

**Comment by enricosada** [comment] 2017-04-20 14:08
@cotyar https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting

**Comment by cotyar** [comment] 2017-04-20 14:09
@enricosada awesome! Thank you

**Comment by cotyar** [comment] 2017-04-20 18:32
@enricosada @alfonsogarciacaro @Krzysztof-Cieslak 
Ok, remerged with the latest version, had a quite irritating time with version of the FAKE and InstallDotNetCore task (paket.lock stuck on the old version of FAKE - 4.56 and build kept failing).
But finally fixed it and after one more dotnet restore in src/Server intellisence started to work!

Thanks again for your help guys and for the awesome toolkit!

**Closed** 2017-04-23 22:17 UTC
